#!/bin/sh

chown root:wheel /sileopirate/data/pirate_strings/Categories.strings
chown root:wheel /sileopirate/data/pirate_strings/Errors.strings
chown root:wheel /sileopirate/data/pirate_strings/Localizable.strings
chown root:wheel /sileopirate/data/pirate_strings/Localizable.stringsdict

echo "Arrrr, matey! Just run sileopirate in ye Terminal to raid Sileo. If ye want to change it back, run sileounpirate. If that doesn't work and ye strings went down to Davy Jones' Locker, reinstall Sileo."
echo ""
echo "Aye, matey! Make sure ye landlubber don't delete /sileopirate . Ye would have to redownload the package if ye do."