#!/bin/sh

VER="0.3"
echo "sileopirate v$VER"
SILEOSTRINGS="/Applications/Sileo.app/Base.lproj"
REPO="https://github.com/The-Hacker894/SileoPirate/blob/master/"
RAW="https://raw.githubusercontent.com/The-Hacker894/SileoPirate/master/"

## Initialzation
if [ ! -d /sileopirate ]; then
    mkdir /sileopirate
fi  
if [ ! -d /sileopirate/data/ ]; then
    mkdir /sileopirate/data/
fi 
if [ -d /sileopirate/data/_pirate-strings/ ]; then
    rm -rfv /sileopirate/data/_pirate-strings/
fi

mkdir /sileopirate/data/_pirate-strings/
## Check connection to GitHub Repo
case "$(curl --insecure -s --max-time 2 -I https://github.com/The-Hacker894/SileoPirate/ | sed 's/^[^ ]*  *\([0-9]\).*/\1/; 1q')" in
    [23]) echo "Internet Connection Sufficient!" ;;
    5) exit 0 ;;
    *) exit 0 ;;
esac

if [ ! -f /sileopirate/sileo-string-backup.zip ]; then
    ## Backing up old strings
    echo "Creatin' ye backup in /sileopirate"
    mkdir /sileopirate/sileo-string-backup/
    echo $VER > /sileopirate/sileo-string-backup/meta.txt

    cp -rfv $SILEOSTRINGS/*.strings /sileopirate/sileo-string-backup/
    cp -rfv $SILEOSTRINGS/*.stringsdict /sileopirate/sileo-string-backup/

    cd /sileopirate
    zip -r9 sileo-string-backup.zip ./sileo-string-backup/
    echo "Arrr! Ye backup be at /sileopirate/sileo-string-backup.zip"
    rm -rfv ./sileo-string-backup/
fi

## Download strings
cd /sileopirate/data/

curl --insecure --silent -o ./pirate.file.list $RAW/pirate.file.list
if [ ! -r ./file.list ]; then
    echo "file.list did not download correctly..."
fi

cd _pirate-strings/

echo "Downloading new resources..."

while read -r line; do
# Reading each line

fname=`basename $line`
echo "Downloading $fname ..."

curl --insecure --silent -o ./$fname $line
chown root:wheel $fname
done < ../pirate.file.list

# Removing old strings
echo "Forcin' ye old strings to walk the plank..."
rm -rfv "$SILEOSTRINGS/*.strings"
rm -rfv "$SILEOSTRINGS/*.stringsdict"

# Replacing with new strings
echo "Raidin' th' Sileo folder..."
cp -afv "/sileopirate/data/_pirate-strings/." "$SILEOSTRINGS/"

# Keeping perms the same
echo "Takin' back what be ours!"
chown root:wheel $SILEOSTRINGS/*.strings
chown root:wheel $SILEOSTRINGS/*.stringsdict

echo "Blow Sileo down for ye effects to work!"
echo ""
echo "If th' installation did not work, run repirate in terminal"