#!/bin/sh

echo "Arrrr, matey! Just run sileopirate in ye Terminal to raid Sileo. If ye want to change it back, run sileounpirate. If that doesn't work and ye strings went down to Davy Jones' Locker, reinstall Sileo."