#!/bin/sh

VER="0.2"
echo "sileopirate v$VER"
SILEOSTRINGS="/Applications/Sileo.app/Base.lproj"
REPO="https://github.com/The-Hacker894/SileoPirate/blob/master/"

CONT=1
if [ ! -f /sileopirate/sileo-string-backup.zip ]; then
    echo "Backup does not exist!"
    CONT=0
fi
walk_plank() {
    # Removing old strings
    echo "Forcin' ye old strings to walk the plank..."
    rm -fv "$SILEOSTRINGS/*.string*"

}
take_ye_own() {
    ## Keep permissions the same
    chown root:wheel $SILEOSTRINGS/*.string*
}
if [ $CONT == 0 ]; then
    case "$(curl --insecure -s --max-time 2 -I https://github.com/The-Hacker894/SileoPirate/ | sed 's/^[^ ]*  *\([0-9]\).*/\1/; 1q')" in
        [23]) echo "Internet Connection Sufficient!" ;;
        5) exit 0 ;;
        *) exit 0 ;;
    esac
    ## Download strings
    mkdir /sileopirate/temp/
    cd /sileopirate/temp/

    curl --insecure --silent -o ./pirate.file.list $REPO/pirate.file.list
    if [ ! -r ./file.list ]; then
        echo "file.list did not download correctly..."
        pause
        start_menu
    fi

    mkdir files
    cd files

    echo "Downloading new resources..."

    while read -r line; do
    # Reading each line

    fname=`basename $line`
    echo "Downloading $fname ..."

    curl --insecure --silent -o ./$fname $line
    chown root:wheel $fname
    done < ../pirate.file.list


    walk_plank

    cp -afv "./." $SILEOSTRINGS

    take_ye_own

    cd /
    rm -rfv /sileopirate

fi
if [ $CONT == 1 ]; then
cd /sileopirate
unzip -o sileo-string-backup.zip

if [ -r /sileopirate/sileo-string-backup/meta.txt ]; then
    META=$(</sileopirate/sileo-string-backup/meta.txt)
    echo "Backup Version: $META"
    echo "SileoPirate Version: $VER"
    echo "Sileo Version: $(dpkg-query -W -f='${Version}\n' org.coolstar.sileo)"
fi

walk_plank

echo "Raidin' th' Sileo folder..."
cp -fv /sileopirate/sileo-string-backup/Categories.strings $SILEOSTRINGS
cp -fv /sileopirate/sileo-string-backup/Errors.strings $SILEOSTRINGS
cp -fv /sileopirate/sileo-string-backup/Localizable.strings $SILEOSTRINGS
cp -fv /sileopirate/sileo-string-backup/Localizable.stringsdict $SILEOSTRINGS

take_ye_own

echo "Aye! Sileo now be reverted back to its original form. Back to work, lads!"
rm -rfv /sileopirate
fi